/* Auto-generated by SeuYacc */
#ifndef MINIC_TAB_H
#define MINIC_TAB_H

#include "symtab.h"
#include "types.h"

#define INT 257
#define FLOAT 258
#define NAME 259
#define STRUCT 260
#define IF 261
#define ELSE 262
#define RETURN 263
#define NUMBER 264
#define LPAR 265
#define RPAR 266
#define LBRACE 267
#define RBRACE 268
#define LBRACK 269
#define RBRACK 270
#define ASSIGN 271
#define SEMICOLON 272
#define COMMA 273
#define DOT 274
#define PLUS 275
#define MINUS 276
#define TIMES 277
#define DIVIDE 278
#define EQUAL 279
#define LOW 280
#define UMINUS 281

typedef union {

	char*		name;
	int		value;
	T_LIST*		tlist;
	T_INFO*		type;
	SYM_INFO*	sym;
	SYM_LIST*	slist;
	
} YYSTYPE;

extern YYSTYPE yylval;

#endif /* MINIC_TAB_H */
