#ifndef MINIC_TAB_H
#define MINIC_TAB_H

/* Token definitions generated by SeuYacc from minic.y */
#define INT     257
#define FLOAT   258
#define NAME    259
#define STRUCT  260
#define IF      261
#define ELSE    262
#define RETURN  263
#define NUMBER  264
#define LPAR    265
#define RPAR    266
#define LBRACE  267
#define RBRACE  268
#define LBRACK  269
#define RBRACK  270
#define ASSIGN  271
#define EQUAL   272
#define SEMICOLON 273
#define COMMA   274
#define DOT     275
#define PLUS    276
#define MINUS   277
#define TIMES   278
#define DIVIDE  279

/* For yacc */
typedef union {
    char* name;
    int value;
    void* tlist;
    void* type;
    void* sym;
    void* slist;
} YYSTYPE;

extern YYSTYPE yylval;

#endif
