#include "LexCodeGen.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <algorithm>

void generateLexCode(const LexSpec& spec, const DFA& dfa,
                     const std::vector<std::string>& rulePostfix,
                     const std::string& outputPath,
                     int wildcardRule) {
    std::ofstream out(outputPath);
    if (!out.is_open()) {
        std::cerr << "Error: cannot create " << outputPath << std::endl;
        return;
    }

    int nStates = static_cast<int>(dfa.states.size());
    int nChars = 256;

    // Build transition table
    std::vector<std::vector<int>> table(nStates, std::vector<int>(nChars, -1));
    for (const auto& s : dfa.states) {
        for (const auto& [c, to] : s.edges) {
            unsigned char uc = (unsigned char)c;
            table[s.number][uc] = to;
        }
    }

    // Build accept state array
    std::vector<int> acceptState(nStates, -1);
    for (const auto& [state, ruleIdx] : dfa.endStatesMap) {
        acceptState[state] = ruleIdx;
    }

    // ====== 1. User code from %{...%} ======
    if (!spec.user_code.empty()) {
        out << spec.user_code << "\n";
    }

    // ====== 2. Generated scanner code ======
    out << R"(/* Generated by SeuLex */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

static char yy_buffer[YY_BUF_SIZE];
static int yy_buf_pos = 0;
static int yy_buf_end = 0;
static int yy_eof = 0;

char* yytext = NULL;
int yyleng = 0;
int yylineno = 1;

)";

    // Accept state array
    out << "static int yy_accept[" << nStates << "];\n\n";

    // Transition table: yy_nxt[state][char]
    out << "static short yy_nxt[" << nStates << "][" << nChars << "] = {\n";
    for (int i = 0; i < nStates; i++) {
        out << "    {";
        for (int j = 0; j < nChars; j++) {
            if (j > 0) out << ",";
            if (j > 0 && j % 32 == 0) out << "\n     ";
            out << table[i][j];
        }
        out << "}";
        if (i < nStates - 1) out << ",";
        out << "\n";
    }
    out << "};\n\n";

    // Input functions
    out << R"(static int yy_getc(void) {
    if (yy_buf_pos >= yy_buf_end) {
        if (yy_eof) return EOF;
        int n = fread(yy_buffer, 1, YY_BUF_SIZE, stdin);
        if (n <= 0) { yy_eof = 1; return EOF; }
        yy_buf_end = n;
        yy_buf_pos = 0;
    }
    return (unsigned char)yy_buffer[yy_buf_pos++];
}

static void yy_ungetc(void) {
    if (yy_buf_pos > 0) yy_buf_pos--;
}

/* yywrap provided by user code if needed */

)";

    // ====== 3. Action code helper ======
    out << "static void yy_init_accept(void) {\n";
    out << "    for (int i = 0; i < " << nStates << "; i++) yy_accept[i] = -1;\n";
    for (const auto& [state, ruleIdx] : dfa.endStatesMap) {
        out << "    yy_accept[" << state << "] = " << ruleIdx << ";\n";
    }
    out << "}\n\n";

    // Write action functions for multi-line actions
    for (size_t i = 0; i < spec.rules.size(); i++) {
        const std::string& action = spec.rules[i].action;
        if (action.find('\n') != std::string::npos) {
            // Multi-line action - write as a helper function
            out << "static int yy_action_" << i << "(void) {\n";
            out << action << "\n";
            out << "    return 0;\n";
            out << "}\n\n";
        }
    }

    // ====== 4. yylex() main function ======
    out << R"(static int yy_accept_initialized = 0;

int yylex(void) {
    if (!yy_accept_initialized) {
        yy_init_accept();
        yy_accept_initialized = 1;
    }
    int yy_state, yy_last_accept, yy_accept_pos, yy_lexeme_len;
    int c;
    char yy_lexeme_buf[YY_BUF_SIZE];

    while (1) {
        yy_state = )" << dfa.startState << R"(;
        yy_last_accept = -1;
        yy_lexeme_len = 0;

        while (1) {
            c = yy_getc();
            if (c == EOF) {
                if (yy_last_accept >= 0) goto found;
                return 0;
            }

            int next = (c >= 0 && c < )" << nChars << R"() ? yy_nxt[yy_state][c] : -1;
            if (next < 0) break;

            yy_state = next;
            yy_lexeme_buf[yy_lexeme_len++] = (char)c;

            if (yy_accept[yy_state] >= 0) {
                yy_last_accept = yy_state;
                yy_accept_pos = yy_lexeme_len;
            }
        }

        if (c != EOF && yy_last_accept < 0) {
            yy_ungetc();
        }

        if (yy_last_accept >= 0) {
            while (yy_lexeme_len > yy_accept_pos) {
                yy_ungetc();
                yy_lexeme_len--;
            }
            yy_lexeme_buf[yy_lexeme_len] = '\0';
            yytext = strdup(yy_lexeme_buf);
            yyleng = yy_lexeme_len;

        found:
            switch (yy_accept[yy_last_accept]) {
)";

    // Generate action cases
    for (size_t i = 0; i < spec.rules.size(); i++) {
        out << "            case " << i << ": /* " << spec.rules[i].regex << " */\n";

        std::string action = spec.rules[i].action;
        if (!action.empty()) {
            if (action.find('\n') != std::string::npos) {
                // Multi-line action: call helper function
                out << "                yy_action_" << i << "();\n";
            } else {
                // Single-line action: inline it
                // Check if it's a "return TOKEN;" style
                if (action.find("return") != std::string::npos) {
                    out << "                " << action << "\n";
                } else if (action.find("break") != std::string::npos) {
                    // Whitespace: break out and continue
                    out << "                break;\n";
                } else {
                    // Other inline action
                    out << "                " << action << "\n";
                    out << "                break;\n";
                }
            }
        }
        out << "                break;\n";
    }

    out << R"(            default:
                break;
            }
            continue;
        } else {
            c = yy_getc();
            if (c == EOF) return 0;
            if (c == '\n') { yylineno++; continue; }
            /* Fallback: match exactly one character */
            yytext = (char*)malloc(2);
            yytext[0] = (char)c;
            yytext[1] = '\0';
            yyleng = 1;
)";

    if (wildcardRule >= 0 && wildcardRule < (int)spec.rules.size()) {
        std::string action = spec.rules[wildcardRule].action;
        // Strip outer braces if present
        std::string trimmed = trim(action);
        if (trimmed.size() >= 2 && trimmed.front() == '{' && trimmed.back() == '}') {
            trimmed = trim(trimmed.substr(1, trimmed.size() - 2));
        }
        out << "            /* Rule " << wildcardRule << " (wildcard) */\n";
        out << "            {\n";
        out << "                " << trimmed << "\n";
        out << "            }\n";
    } else {
        out << "            fprintf(stderr, \"Lex error on line %d: unexpected char '%c' (0x%02x)\\n\",\n";
        out << "                    yylineno, (c >= 32 && c < 127 ? c : '?'), c);\n";
    }
    out << "            continue;\n";
    out << R"(        }
    }
}
)";

    // ====== 5. Standalone main() for testing ======
    out << R"(
int main(int argc, char* argv[]) {
    if (argc > 1) {
        FILE* f = fopen(argv[1], "r");
        if (f) {
            yy_buf_end = fread(yy_buffer, 1, YY_BUF_SIZE, f);
            fclose(f);
            yy_buf_pos = 0;
        }
    }
    yy_init_accept();
    yylex();
    return 0;
}
)";

    // ====== 6. User functions ======
    if (!spec.user_functions.empty()) {
        out << "\n/* === User functions === */\n";
        out << spec.user_functions;
    }

    out.close();
    std::cout << "Generated " << outputPath << " (" << nStates << " DFA states)" << std::endl;
}
